version: '3.8'
name: tp2_local

services:
  tp_back:
    container_name: tp-back-local
    build: 
      context: .
      dockerfile: ./docker/local.dockerfile
    ports:
      - "${TYPOGRAPH_SERVICE_PORT}:8080"
    volumes:
      - ./:/usr/src/app
    depends_on:
      - tp-db
    env_file:
      - .env

  tp-db:
    container_name: tp-db-local
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "${TYPOGRAPH_SERVICE_DB_PORT}:5432"
    volumes:
      - tp-db:/var/lib/postgresql/data

volumes:
  tp-db:
