version: '3.8'
name: tp_prod

services:
  typograph_back:
    container_name: typograph_back
    build: 
      context: .
      dockerfile: ./docker/prod.dockerfile
    ports:
      - "${TYPOGRAPH_SERVICE_PORT}:8080"
    volumes:
      - ./:/usr/src/app
    depends_on:
      - tp-db
    env_file:
      - .env

  tp-db:
    container_name: tp-db
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "${TYPOGRAPH_SERVICE_DB_PORT}:5432"
    volumes:
      - tp-db:/var/lib/postgresql/data

volumes:
  tp-db:
