env: "local" # local, dev, prod
http:
  address: "localhost:8000"
  timeout: 4s
  idle_timeout: 60s
postgres:
  url: "postgres://postgres:mysecretpassword@localhost:5432/tp_db?sslmode=disable"
  migrations_path: "./migrations"
jwt:
  secret_key: "local"